import type { CharacterInfo } from './types';

/**
 * Curated character index covering every unique character in ENTRIES' simplified
 * headwords (src/api/data.ts). Radical/component/stroke data is hand-checked against
 * standard mainland dictionary conventions; components are a *direct top-level*
 * decomposition only (not recursive), and are left as `[]` where a clean, confident
 * split isn't well established rather than guessing — per the project rule that a
 * wrong decomposition is worse than a missing one. frequencyRank is a rough relative
 * ordering for sort purposes only, not an authoritative corpus statistic.
 */
export const CHARACTERS: CharacterInfo[] = [
  { char: '银', traditional: '銀', readings: [{ pinyin: 'yin2', glosses: ['silver', 'relating to money or banking'] }], radical: '钅', components: ['钅', '艮'], strokeCount: 11, hskLevel: 3, frequencyRank: 900 },
  { char: '行', traditional: '行', readings: [{ pinyin: 'xing2', glosses: ['to walk', 'to be OK', 'capable'] }, { pinyin: 'hang2', glosses: ['row', 'profession', 'firm'] }], radical: '行', components: ['彳', '亍'], strokeCount: 6, hskLevel: 3, frequencyRank: 200 },
  { char: '合', traditional: '合', readings: [{ pinyin: 'he2', glosses: ['to combine', 'to suit', 'whole'] }], radical: '口', components: ['人', '一', '口'], strokeCount: 6, hskLevel: 3, frequencyRank: 500 },
  { char: '同', traditional: '同', readings: [{ pinyin: 'tong2', glosses: ['same', 'together', 'with'] }], radical: '口', components: ['冂', '一', '口'], strokeCount: 6, hskLevel: 1, frequencyRank: 250 },
  { char: '意', traditional: '意', readings: [{ pinyin: 'yi4', glosses: ['idea', 'meaning', 'intention'] }], radical: '心', components: ['音', '心'], strokeCount: 13, hskLevel: 2, frequencyRank: 400 },
  { char: '思', traditional: '思', readings: [{ pinyin: 'si1', glosses: ['to think', 'to consider', 'thought'] }], radical: '心', components: ['田', '心'], strokeCount: 9, hskLevel: 2, frequencyRank: 450 },
  { char: '打', traditional: '打', readings: [{ pinyin: 'da3', glosses: ['to hit', 'to play', 'to make (a call)'] }], radical: '扌', components: ['扌', '丁'], strokeCount: 5, hskLevel: 1, frequencyRank: 300 },
  { char: '方', traditional: '方', readings: [{ pinyin: 'fang1', glosses: ['square', 'direction', 'method'] }], radical: '方', components: [], strokeCount: 4, hskLevel: 3, frequencyRank: 350 },
  { char: '便', traditional: '便', readings: [{ pinyin: 'bian4', glosses: ['convenient', 'then'] }, { pinyin: 'pian2', glosses: ['cheap (便宜)'] }], radical: '亻', components: ['亻', '更'], strokeCount: 9, hskLevel: 3, frequencyRank: 1400 },
  { char: '关', traditional: '關', readings: [{ pinyin: 'guan1', glosses: ['to close', 'to turn off', 'to relate to'] }], radical: '八', components: ['丷', '天'], strokeCount: 6, hskLevel: 3, frequencyRank: 700 },
  { char: '系', traditional: '係', readings: [{ pinyin: 'xi4', glosses: ['system', 'to relate', 'to tie'] }], radical: '糸', components: ['丿', '糸'], strokeCount: 7, hskLevel: 3, frequencyRank: 900 },
  { char: '面', traditional: '面', readings: [{ pinyin: 'mian4', glosses: ['face', 'surface', 'noodle'] }], radical: '面', components: [], strokeCount: 9, hskLevel: 2, frequencyRank: 550 },
  { char: '子', traditional: '子', readings: [{ pinyin: 'zi3', glosses: ['child', 'seed', 'noun suffix'] }], radical: '子', components: [], strokeCount: 3, hskLevel: 1, frequencyRank: 150 },
  { char: '精', traditional: '精', readings: [{ pinyin: 'jing1', glosses: ['refined', 'essence', 'spirit'] }], radical: '米', components: ['米', '青'], strokeCount: 14, hskLevel: 4, frequencyRank: 2200 },
  { char: '神', traditional: '神', readings: [{ pinyin: 'shen2', glosses: ['god', 'spirit', 'magical'] }], radical: '礻', components: ['礻', '申'], strokeCount: 9, hskLevel: 4, frequencyRank: 1200 },
  { char: '把', traditional: '把', readings: [{ pinyin: 'ba3', glosses: ['to hold', 'to grasp', 'measure word; particle'] }], radical: '扌', components: ['扌', '巴'], strokeCount: 7, hskLevel: 2, frequencyRank: 600 },
  { char: '握', traditional: '握', readings: [{ pinyin: 'wo4', glosses: ['to hold', 'to grasp'] }], radical: '扌', components: ['扌', '屋'], strokeCount: 12, hskLevel: 5, frequencyRank: 3200 },
  { char: '诉', traditional: '訴', readings: [{ pinyin: 'su4', glosses: ['to tell', 'to complain', 'to sue'] }], radical: '讠', components: ['讠', '斥'], strokeCount: 7, hskLevel: 4, frequencyRank: 2600 },
  { char: '讼', traditional: '訟', readings: [{ pinyin: 'song4', glosses: ['lawsuit', 'to litigate'] }], radical: '讠', components: ['讠', '公'], strokeCount: 6, frequencyRank: 6300 },
  { char: '仲', traditional: '仲', readings: [{ pinyin: 'zhong4', glosses: ['second (of brothers)', 'to mediate'] }], radical: '亻', components: ['亻', '中'], strokeCount: 6, frequencyRank: 6800 },
  { char: '裁', traditional: '裁', readings: [{ pinyin: 'cai2', glosses: ['to cut out', 'to reduce', 'to judge'] }], radical: '衣', components: ['戈', '衣'], strokeCount: 12, frequencyRank: 5400 },
  { char: '侵', traditional: '侵', readings: [{ pinyin: 'qin1', glosses: ['to invade', 'to infringe'] }], radical: '亻', components: ['亻', '又'], strokeCount: 9, frequencyRank: 4900 },
  { char: '权', traditional: '權', readings: [{ pinyin: 'quan2', glosses: ['power', 'right', 'authority'] }], radical: '木', components: ['木', '又'], strokeCount: 6, hskLevel: 4, frequencyRank: 1500 },
  { char: '原', traditional: '原', readings: [{ pinyin: 'yuan2', glosses: ['original', 'source', 'to forgive'] }], radical: '厂', components: ['厂', '白'], strokeCount: 10, hskLevel: 3, frequencyRank: 800 },
  { char: '告', traditional: '告', readings: [{ pinyin: 'gao4', glosses: ['to tell', 'to sue', 'to announce'] }], radical: '口', components: ['牛', '口'], strokeCount: 7, hskLevel: 3, frequencyRank: 1000 },
  { char: '被', traditional: '被', readings: [{ pinyin: 'bei4', glosses: ['quilt', 'passive marker', 'to cover'] }], radical: '衤', components: ['衤', '皮'], strokeCount: 10, hskLevel: 3, frequencyRank: 700 },
  { char: '履', traditional: '履', readings: [{ pinyin: 'lv3', glosses: ['shoe', 'to walk on', 'to fulfill'] }], radical: '尸', components: ['尸', '复'], strokeCount: 15, frequencyRank: 5100 },
  { char: '生', traditional: '生', readings: [{ pinyin: 'sheng1', glosses: ['to be born', 'life', 'raw'] }], radical: '生', components: [], strokeCount: 5, hskLevel: 1, frequencyRank: 90 },
  { char: '效', traditional: '效', readings: [{ pinyin: 'xiao4', glosses: ['effect', 'to imitate'] }], radical: '攵', components: ['交', '攵'], strokeCount: 10, hskLevel: 4, frequencyRank: 1800 },
  { char: '违', traditional: '違', readings: [{ pinyin: 'wei2', glosses: ['to violate', 'to disobey'] }], radical: '辶', components: ['辶', '韦'], strokeCount: 7, frequencyRank: 4400 },
  { char: '约', traditional: '約', readings: [{ pinyin: 'yue1', glosses: ['to agree', 'approximately', 'appointment'] }], radical: '纟', components: ['纟', '勺'], strokeCount: 6, hskLevel: 4, frequencyRank: 1300 },
  { char: '赔', traditional: '賠', readings: [{ pinyin: 'pei2', glosses: ['to compensate', 'to lose money'] }], radical: '贝', components: ['贝', '咅'], strokeCount: 12, frequencyRank: 4100 },
  { char: '偿', traditional: '償', readings: [{ pinyin: 'chang2', glosses: ['to repay', 'to compensate'] }], radical: '亻', components: ['亻', '尝'], strokeCount: 11, frequencyRank: 4800 },
  { char: '股', traditional: '股', readings: [{ pinyin: 'gu3', glosses: ['share (stock)', 'thigh', 'strand'] }], radical: '月', components: ['月', '殳'], strokeCount: 8, hskLevel: 6, frequencyRank: 2100 },
  { char: '票', traditional: '票', readings: [{ pinyin: 'piao4', glosses: ['ticket', 'ballot', 'note'] }], radical: '示', components: ['覀', '示'], strokeCount: 11, hskLevel: 3, frequencyRank: 1600 },
  { char: '汇', traditional: '匯', readings: [{ pinyin: 'hui4', glosses: ['to converge', 'to remit', 'currency exchange'] }], radical: '氵', components: ['氵', '匚'], strokeCount: 5, frequencyRank: 3500 },
  { char: '率', traditional: '率', readings: [{ pinyin: 'lv4', glosses: ['rate', 'ratio'] }, { pinyin: 'shuai4', glosses: ['to lead', 'to command'] }], radical: '玄', components: ['玄', '十'], strokeCount: 11, frequencyRank: 2900 },
  { char: '融', traditional: '融', readings: [{ pinyin: 'rong2', glosses: ['to melt', 'to blend', 'finance (融资)'] }], radical: '虫', components: ['鬲', '虫'], strokeCount: 16, frequencyRank: 3300 },
  { char: '资', traditional: '資', readings: [{ pinyin: 'zi1', glosses: ['capital', 'resources', 'funds'] }], radical: '贝', components: ['次', '贝'], strokeCount: 10, hskLevel: 4, frequencyRank: 1100 },
  { char: '税', traditional: '稅', readings: [{ pinyin: 'shui4', glosses: ['tax'] }], radical: '禾', components: ['禾', '兑'], strokeCount: 12, frequencyRank: 3000 },
  { char: '供', traditional: '供', readings: [{ pinyin: 'gong1', glosses: ['to supply', 'to provide'] }, { pinyin: 'gong4', glosses: ['to confess'] }], radical: '亻', components: ['亻', '共'], strokeCount: 8, hskLevel: 5, frequencyRank: 2000 },
  { char: '应', traditional: '應', readings: [{ pinyin: 'ying1', glosses: ['should', 'ought to'] }, { pinyin: 'ying4', glosses: ['to respond', 'to answer'] }], radical: '广', components: ['广'], strokeCount: 7, hskLevel: 2, frequencyRank: 260 },
  { char: '链', traditional: '鏈', readings: [{ pinyin: 'lian4', glosses: ['chain'] }], radical: '钅', components: ['钅', '连'], strokeCount: 12, frequencyRank: 4600 },
  { char: '谈', traditional: '談', readings: [{ pinyin: 'tan2', glosses: ['to talk', 'to chat'] }], radical: '讠', components: ['讠', '炎'], strokeCount: 10, hskLevel: 5, frequencyRank: 1900 },
  { char: '判', traditional: '判', readings: [{ pinyin: 'pan4', glosses: ['to judge', 'to sentence'] }], radical: '刂', components: ['半', '刂'], strokeCount: 7, frequencyRank: 3100 },
  { char: '疫', traditional: '疫', readings: [{ pinyin: 'yi4', glosses: ['epidemic', 'plague'] }], radical: '疒', components: ['疒', '殳'], strokeCount: 9, frequencyRank: 3800 },
  { char: '苗', traditional: '苗', readings: [{ pinyin: 'miao2', glosses: ['sprout', 'seedling', 'vaccine (疫苗)'] }], radical: '艹', components: ['艹', '田'], strokeCount: 8, frequencyRank: 3600 },
  { char: '临', traditional: '臨', readings: [{ pinyin: 'lin2', glosses: ['to face', 'to overlook', 'about to'] }], radical: '丨', components: [], strokeCount: 9, hskLevel: 5, frequencyRank: 2400 },
  { char: '床', traditional: '床', readings: [{ pinyin: 'chuang2', glosses: ['bed'] }], radical: '广', components: ['广', '木'], strokeCount: 7, hskLevel: 1, frequencyRank: 1700 },
  { char: '高', traditional: '高', readings: [{ pinyin: 'gao1', glosses: ['tall', 'high'] }], radical: '高', components: [], strokeCount: 10, hskLevel: 1, frequencyRank: 220 },
  { char: '血', traditional: '血', readings: [{ pinyin: 'xue4', glosses: ['blood'] }, { pinyin: 'xie3', glosses: ['blood (colloquial)'] }], radical: '血', components: [], strokeCount: 6, hskLevel: 4, frequencyRank: 2300 },
  { char: '压', traditional: '壓', readings: [{ pinyin: 'ya1', glosses: ['to press', 'pressure'] }], radical: '厂', components: ['厂', '土'], strokeCount: 6, hskLevel: 4, frequencyRank: 2500 },
  { char: '人', traditional: '人', readings: [{ pinyin: 'ren2', glosses: ['person', 'people'] }], radical: '人', components: [], strokeCount: 2, hskLevel: 1, frequencyRank: 10 },
  { char: '工', traditional: '工', readings: [{ pinyin: 'gong1', glosses: ['work', 'labor', 'craft'] }], radical: '工', components: [], strokeCount: 3, hskLevel: 2, frequencyRank: 320 },
  { char: '智', traditional: '智', readings: [{ pinyin: 'zhi4', glosses: ['wisdom', 'intelligence'] }], radical: '日', components: ['知', '日'], strokeCount: 12, frequencyRank: 3400 },
  { char: '能', traditional: '能', readings: [{ pinyin: 'neng2', glosses: ['can', 'ability', 'energy'] }], radical: '月', components: ['厶', '月'], strokeCount: 10, hskLevel: 1, frequencyRank: 140 },
  { char: '算', traditional: '算', readings: [{ pinyin: 'suan4', glosses: ['to calculate', 'to count', 'to plan'] }], radical: '竹', components: ['竹', '目', '廾'], strokeCount: 14, hskLevel: 3, frequencyRank: 1450 },
  { char: '法', traditional: '法', readings: [{ pinyin: 'fa3', glosses: ['law', 'method'] }], radical: '氵', components: ['氵', '去'], strokeCount: 8, hskLevel: 3, frequencyRank: 380 },
  { char: '芯', traditional: '芯', readings: [{ pinyin: 'xin1', glosses: ['core', 'chip (芯片)'] }], radical: '艹', components: ['艹', '心'], strokeCount: 7, frequencyRank: 5700 },
  { char: '片', traditional: '片', readings: [{ pinyin: 'pian4', glosses: ['slice', 'piece', 'film'] }], radical: '片', components: [], strokeCount: 4, hskLevel: 3, frequencyRank: 1250 },
  { char: '数', traditional: '數', readings: [{ pinyin: 'shu4', glosses: ['number'] }, { pinyin: 'shu3', glosses: ['to count'] }], radical: '攵', components: ['娄', '攵'], strokeCount: 13, hskLevel: 3, frequencyRank: 850 },
  { char: '据', traditional: '據', readings: [{ pinyin: 'ju4', glosses: ['according to', 'evidence'] }], radical: '扌', components: ['扌', '居'], strokeCount: 11, hskLevel: 5, frequencyRank: 2000 },
  { char: '库', traditional: '庫', readings: [{ pinyin: 'ku4', glosses: ['warehouse', 'database (数据库)'] }], radical: '广', components: ['广', '车'], strokeCount: 7, frequencyRank: 3900 },
  { char: '画', traditional: '畫', readings: [{ pinyin: 'hua4', glosses: ['to draw', 'picture', 'stroke (of a character)'] }], radical: '一', components: ['田'], strokeCount: 8, hskLevel: 3, frequencyRank: 1350 },
  { char: '蛇', traditional: '蛇', readings: [{ pinyin: 'she2', glosses: ['snake'] }], radical: '虫', components: ['虫', '它'], strokeCount: 11, hskLevel: 5, frequencyRank: 4700 },
  { char: '添', traditional: '添', readings: [{ pinyin: 'tian1', glosses: ['to add'] }], radical: '氵', components: ['氵', '忝'], strokeCount: 11, frequencyRank: 5300 },
  { char: '足', traditional: '足', readings: [{ pinyin: 'zu2', glosses: ['foot', 'enough', 'sufficient'] }], radical: '足', components: [], strokeCount: 7, hskLevel: 2, frequencyRank: 950 },
  { char: '亡', traditional: '亡', readings: [{ pinyin: 'wang2', glosses: ['to die', 'to flee', 'lost'] }], radical: '亠', components: [], strokeCount: 3, frequencyRank: 4200 },
  { char: '羊', traditional: '羊', readings: [{ pinyin: 'yang2', glosses: ['sheep', 'goat'] }], radical: '羊', components: [], strokeCount: 6, hskLevel: 4, frequencyRank: 2700 },
  { char: '补', traditional: '補', readings: [{ pinyin: 'bu3', glosses: ['to mend', 'to patch', 'to supplement'] }], radical: '衤', components: ['衤', '卜'], strokeCount: 7, hskLevel: 5, frequencyRank: 2600 },
  { char: '牢', traditional: '牢', readings: [{ pinyin: 'lao2', glosses: ['prison', 'pen (livestock)', 'durable'] }], radical: '宀', components: ['宀', '牛'], strokeCount: 7, frequencyRank: 5900 },
  { char: '实', traditional: '實', readings: [{ pinyin: 'shi2', glosses: ['real', 'true', 'solid'] }], radical: '宀', components: ['宀'], strokeCount: 8, hskLevel: 3, frequencyRank: 780 },
  { char: '事', traditional: '事', readings: [{ pinyin: 'shi4', glosses: ['matter', 'affair', 'to serve'] }], radical: '一', components: [], strokeCount: 8, hskLevel: 1, frequencyRank: 240 },
  { char: '求', traditional: '求', readings: [{ pinyin: 'qiu2', glosses: ['to seek', 'to request'] }], radical: '水', components: [], strokeCount: 7, hskLevel: 4, frequencyRank: 1050 },
  { char: '是', traditional: '是', readings: [{ pinyin: 'shi4', glosses: ['to be', 'yes', 'right'] }], radical: '日', components: ['日'], strokeCount: 9, hskLevel: 1, frequencyRank: 20 },
  { char: '一', traditional: '一', readings: [{ pinyin: 'yi1', glosses: ['one'] }], radical: '一', components: [], strokeCount: 1, hskLevel: 1, frequencyRank: 1 },
  { char: '丝', traditional: '絲', readings: [{ pinyin: 'si1', glosses: ['silk', 'thread', 'a tiny bit'] }], radical: '纟', components: [], strokeCount: 6, hskLevel: 5, frequencyRank: 2800 },
  { char: '不', traditional: '不', readings: [{ pinyin: 'bu4', glosses: ['not', 'no'] }], radical: '一', components: [], strokeCount: 4, hskLevel: 1, frequencyRank: 5 },
  { char: '苟', traditional: '苟', readings: [{ pinyin: 'gou3', glosses: ['careless', 'if (classical)'] }], radical: '艹', components: ['艹', '句'], strokeCount: 8, frequencyRank: 6600 },
  { char: '靠', traditional: '靠', readings: [{ pinyin: 'kao4', glosses: ['to lean on', 'to depend on', 'reliable (靠谱)'] }], radical: '非', components: ['告', '非'], strokeCount: 15, frequencyRank: 3700 },
  { char: '谱', traditional: '譜', readings: [{ pinyin: 'pu3', glosses: ['musical score', 'chart', 'sense of certainty (靠谱)'] }], radical: '讠', components: ['讠', '普'], strokeCount: 14, frequencyRank: 4300 },
  { char: '撒', traditional: '撒', readings: [{ pinyin: 'sa1', glosses: ['to let go', 'to act (coquettishly, 撒娇)'] }, { pinyin: 'sa3', glosses: ['to sprinkle', 'to scatter'] }], radical: '扌', components: ['扌', '散'], strokeCount: 15, frequencyRank: 5000 },
  { char: '娇', traditional: '嬌', readings: [{ pinyin: 'jiao1', glosses: ['delicate', 'charming', 'pampered'] }], radical: '女', components: ['女', '乔'], strokeCount: 9, frequencyRank: 5200 },
  { char: '鉴', traditional: '鑒', readings: [{ pinyin: 'jian4', glosses: ['mirror', 'to reflect on', 'in view of (鉴于)'] }], radical: '金', components: ['金'], strokeCount: 13, frequencyRank: 4000 },
  { char: '于', traditional: '於', readings: [{ pinyin: 'yu2', glosses: ['at', 'in', 'to (formal)'] }], radical: '二', components: [], strokeCount: 3, hskLevel: 4, frequencyRank: 500 },
  { char: '之', traditional: '之', readings: [{ pinyin: 'zhi1', glosses: ['possessive/linking particle (classical)'] }], radical: '丶', components: [], strokeCount: 3, hskLevel: 5, frequencyRank: 300 },
  { char: '际', traditional: '際', readings: [{ pinyin: 'ji4', glosses: ['border', 'occasion', 'inter- (国际)'] }], radical: '阝', components: ['阝', '示'], strokeCount: 7, hskLevel: 4, frequencyRank: 1550 },
  { char: '政', traditional: '政', readings: [{ pinyin: 'zheng4', glosses: ['politics', 'government'] }], radical: '攵', components: ['正', '攵'], strokeCount: 9, hskLevel: 5, frequencyRank: 780 },
  { char: '策', traditional: '策', readings: [{ pinyin: 'ce4', glosses: ['plan', 'scheme', 'policy'] }], radical: '竹', components: ['竹', '朿'], strokeCount: 12, hskLevel: 5, frequencyRank: 1650 },
  { char: '改', traditional: '改', readings: [{ pinyin: 'gai3', glosses: ['to change', 'to reform', 'to correct'] }], radical: '攵', components: ['己', '攵'], strokeCount: 7, hskLevel: 3, frequencyRank: 900 },
  { char: '革', traditional: '革', readings: [{ pinyin: 'ge2', glosses: ['leather', 'to reform'] }], radical: '革', components: [], strokeCount: 9, hskLevel: 5, frequencyRank: 1750 },
  { char: '环', traditional: '環', readings: [{ pinyin: 'huan2', glosses: ['ring', 'loop', 'environment (环境)'] }], radical: '王', components: ['王'], strokeCount: 8, hskLevel: 4, frequencyRank: 1500 },
  { char: '境', traditional: '境', readings: [{ pinyin: 'jing4', glosses: ['border', 'condition', 'environment'] }], radical: '土', components: ['土', '竟'], strokeCount: 14, hskLevel: 4, frequencyRank: 1350 },
  { char: '可', traditional: '可', readings: [{ pinyin: 'ke3', glosses: ['can', 'may', 'approve of'] }], radical: '口', components: ['口'], strokeCount: 5, hskLevel: 1, frequencyRank: 60 },
  { char: '持', traditional: '持', readings: [{ pinyin: 'chi2', glosses: ['to hold', 'to maintain', 'to persist'] }], radical: '扌', components: ['扌', '寺'], strokeCount: 9, hskLevel: 4, frequencyRank: 1000 },
  { char: '续', traditional: '續', readings: [{ pinyin: 'xu4', glosses: ['to continue'] }], radical: '纟', components: ['纟'], strokeCount: 11, hskLevel: 4, frequencyRank: 1900 },
  { char: '发', traditional: '發', readings: [{ pinyin: 'fa1', glosses: ['to send out', 'to issue', 'to develop'] }], radical: '又', components: [], strokeCount: 5, hskLevel: 1, frequencyRank: 130 },
  { char: '展', traditional: '展', readings: [{ pinyin: 'zhan3', glosses: ['to open out', 'to develop', 'exhibition'] }], radical: '尸', components: ['尸'], strokeCount: 10, hskLevel: 4, frequencyRank: 1400 },
  { char: '碳', traditional: '碳', readings: [{ pinyin: 'tan4', glosses: ['carbon'] }], radical: '石', components: ['石', '炭'], strokeCount: 14, frequencyRank: 5600 },
  { char: '中', traditional: '中', readings: [{ pinyin: 'zhong1', glosses: ['middle', 'center', 'China (中国)'] }], radical: '丨', components: [], strokeCount: 4, hskLevel: 1, frequencyRank: 30 },
  { char: '和', traditional: '和', readings: [{ pinyin: 'he2', glosses: ['and', 'harmony', 'peace'] }], radical: '口', components: ['禾', '口'], strokeCount: 8, hskLevel: 1, frequencyRank: 70 },
  { char: '老', traditional: '老', readings: [{ pinyin: 'lao3', glosses: ['old'] }], radical: '老', components: [], strokeCount: 6, hskLevel: 1, frequencyRank: 340 },
  { char: '百', traditional: '百', readings: [{ pinyin: 'bai3', glosses: ['hundred'] }], radical: '白', components: [], strokeCount: 6, hskLevel: 2, frequencyRank: 460 },
  { char: '姓', traditional: '姓', readings: [{ pinyin: 'xing4', glosses: ['surname'] }], radical: '女', components: ['女', '生'], strokeCount: 8, hskLevel: 1, frequencyRank: 1600 },
  { char: '干', traditional: '幹', readings: [{ pinyin: 'gan1', glosses: ['dry', 'stem'] }, { pinyin: 'gan4', glosses: ['to do', 'to work'] }], radical: '干', components: [], strokeCount: 3, hskLevel: 4, frequencyRank: 1000 },
  { char: '部', traditional: '部', readings: [{ pinyin: 'bu4', glosses: ['part', 'department', 'ministry'] }], radical: '阝', components: ['咅', '阝'], strokeCount: 10, hskLevel: 3, frequencyRank: 420 },
  { char: '单', traditional: '單', readings: [{ pinyin: 'dan1', glosses: ['single', 'only', 'simple'] }], radical: '十', components: [], strokeCount: 8, hskLevel: 3, frequencyRank: 950 },
  { char: '位', traditional: '位', readings: [{ pinyin: 'wei4', glosses: ['position', 'place', 'measure word for people'] }], radical: '亻', components: ['亻', '立'], strokeCount: 7, hskLevel: 3, frequencyRank: 480 },
  { char: '户', traditional: '戶', readings: [{ pinyin: 'hu4', glosses: ['door', 'household'] }], radical: '户', components: [], strokeCount: 4, hskLevel: 4, frequencyRank: 2200 },
  { char: '口', traditional: '口', readings: [{ pinyin: 'kou3', glosses: ['mouth', 'opening'] }], radical: '口', components: [], strokeCount: 3, hskLevel: 1, frequencyRank: 400 },
  { char: '小', traditional: '小', readings: [{ pinyin: 'xiao3', glosses: ['small'] }], radical: '小', components: [], strokeCount: 3, hskLevel: 1, frequencyRank: 160 },
  { char: '康', traditional: '康', readings: [{ pinyin: 'kang1', glosses: ['healthy', 'peaceful'] }], radical: '广', components: ['广'], strokeCount: 11, frequencyRank: 3500 },
  { char: '落', traditional: '落', readings: [{ pinyin: 'luo4', glosses: ['to fall', 'to leave behind', 'to settle'] }], radical: '艹', components: ['艹', '洛'], strokeCount: 12, hskLevel: 5, frequencyRank: 1800 },
  { char: '推', traditional: '推', readings: [{ pinyin: 'tui1', glosses: ['to push', 'to advance', 'to推 推荐 recommend'] }], radical: '扌', components: ['扌', '隹'], strokeCount: 11, hskLevel: 3, frequencyRank: 1150 },
  { char: '进', traditional: '進', readings: [{ pinyin: 'jin4', glosses: ['to advance', 'to enter'] }], radical: '辶', components: ['辶', '井'], strokeCount: 7, hskLevel: 2, frequencyRank: 280 },
  { char: '出', traditional: '出', readings: [{ pinyin: 'chu1', glosses: ['to go out', 'to come out', 'to exceed'] }], radical: '凵', components: [], strokeCount: 5, hskLevel: 1, frequencyRank: 100 },
  { char: '台', traditional: '臺', readings: [{ pinyin: 'tai2', glosses: ['platform', 'stand', 'measure word'] }], radical: '口', components: [], strokeCount: 5, hskLevel: 4, frequencyRank: 1250 },
  { char: '该', traditional: '該', readings: [{ pinyin: 'gai1', glosses: ['should', 'that (formal)'] }], radical: '讠', components: ['讠', '亥'], strokeCount: 8, hskLevel: 4, frequencyRank: 1050 },
  { char: '问', traditional: '問', readings: [{ pinyin: 'wen4', glosses: ['to ask'] }], radical: '门', components: ['门', '口'], strokeCount: 6, hskLevel: 1, frequencyRank: 190 },
  { char: '题', traditional: '題', readings: [{ pinyin: 'ti2', glosses: ['topic', 'question', 'problem'] }], radical: '页', components: ['是', '页'], strokeCount: 15, hskLevel: 2, frequencyRank: 470 },
  { char: '翻', traditional: '翻', readings: [{ pinyin: 'fan1', glosses: ['to turn over', 'to translate (翻译)'] }], radical: '羽', components: ['番', '羽'], strokeCount: 18, hskLevel: 4, frequencyRank: 3100 },
  { char: '译', traditional: '譯', readings: [{ pinyin: 'yi4', glosses: ['to translate', 'to interpret'] }], radical: '讠', components: ['讠'], strokeCount: 7, hskLevel: 4, frequencyRank: 3300 },
];

/**
 * Every distinct component used across CHARACTERS' `components` arrays, with a
 * best-effort stroke count for the picker's stroke-count grouping. (Two-part
 * decompositions mostly sum to their character's strokeCount as a cross-check;
 * a few characters use a partial one-component breakdown by design — see the
 * top-of-file note — so their sums intentionally fall short.)
 */
export const COMPONENT_STROKES: Record<string, number> = {
  一: 1, 丨: 1, 丿: 1, 丶: 1,
  二: 2, 人: 2, 亻: 2, 丷: 2, 冂: 2, 刂: 2, 匚: 2, 卜: 2, 又: 2, 厂: 2, 十: 2, 讠: 2, 阝: 2, 厶: 2,
  口: 3, 土: 3, 女: 3, 子: 3, 宀: 3, 干: 3, 广: 3, 廾: 3, 彳: 3, 亍: 3, 纟: 3, 辶: 3, 艹: 3, 己: 3, 尸: 3, 勺: 3, 门: 3, 扌: 3, 氵: 3,
  心: 4, 戈: 4, 攵: 4, 木: 4, 月: 4, 殳: 4, 牛: 4, 中: 4, 车: 4, 韦: 4, 巴: 4, 丁: 2, 天: 4, 公: 4, 井: 4, 礻: 4, 王: 4, 日: 4, 贝: 4,
  玄: 5, 生: 5, 田: 5, 疒: 5, 白: 5, 皮: 5, 目: 5, 石: 5, 示: 5, 禾: 5, 斥: 5, 申: 5, 半: 5, 句: 5, 去: 5, 衤: 5, 立: 5, 正: 5, 它: 5,
  竹: 6, 米: 6, 糸: 6, 交: 6, 共: 6, 寺: 6, 乔: 6, 页: 6, 羽: 6, 衣: 6, 次: 6, 朿: 6, 覀: 6, 亥: 6, 虫: 6, 艮: 6,
  兑: 7, 连: 7, 告: 7, 更: 7,
  知: 8, 咅: 8, 居: 8, 隹: 8, 炎: 8, 青: 8, 金: 8, 忝: 8, 非: 8,
  音: 9, 屋: 9, 复: 9, 尝: 9, 炭: 9, 是: 9, 娄: 9, 洛: 9,
  鬲: 10,
  竟: 11,
  普: 12, 散: 12, 番: 12,
  钅: 5,
};
